@startuml

actor "Librarian" as U
participant "BookCommand[w]" as BMW
participant "BookCommand[i]" as BMI
participant "Book Query[j]" as BQ
participant "Lending Command[k]" as LC
participant "Lending Query[l]" as LQ

participant "Message Broker" as MB

U -> BMW : PATCH /book (isbn, title, genre,\n\t\t description, author/s)
activate BMW

BMW -> BMW : update (isbn, title, genre,\n\t description, author/s)

BMW -> MB : publishBookUpdated(book)
activate MB

BMW --> U: 200

MB -> BMW : notify(book)
deactivate BMW

MB -> BMI : notify(book)
activate BMI
BMI --> BMI : save (book)
deactivate BMI

MB -> BQ : notify(book)
activate BQ
BQ --> BQ : save (book)
deactivate BQ

MB -> LC : notify(book)
activate LC
LC --> LC : save (book)
deactivate LC

MB -> LQ : notify(book)
activate LQ
LQ --> LQ : save (book)
deactivate LQ

deactivate MB

footer Todas as User Stories que seguem o padrão PATCH terão um diagrama deste género.

@enduml
